### ISSUE TITLE
파일 형식의 답안 소스코드 제출 인터페이스 구현

### ISSUE THREAD

**Issue by fhqlatm** [hyunchan-park/JOTA-dmoj-online-judge#13]
> [JOTA Judge Server Issue #05](https://github.com/hyunchan-park/JOTA-dmoj-judge-server/issues/5)
>
> **답안 제출 시 여러 소스코드로 작성하여 제출 가능하도록 구현**
>
> Submitter 측에서 source code 제출 시 single source code 가 아닌 multiple source codes 제출 가능하도록 구현

**JOTA 파일 형식 소스코드 제출 지원**

​	위 Judge Server Issue에 따라 여러 소스코드로 답안을 제출하는 방식을 multiple source codes 파일로 제출하도록 구현하고자 합니다.

​	따라서 JOTA 웹사이트에 파일 형식의 source code 를 제출하여 채점할 수 있도록 Site-side에서의 인터페이스 구현이 필요합니다.

​	

**Referencing Documentation**

* django docs: https://docs.djangoproject.com/en/3.2/topics/http/file-uploads/

**Comment by jubin-park** [comment]
[JOTA-multiple-submission-site-ui.pdf](https://github.com/hyunchan-park/JOTA-dmoj-online-judge/files/6834314/JOTA-multiple-submission-site-ui.pdf)

Site Submission 관련 UI 시안을 담은 파일을 첨부합니다.

**Comment by jubin-park** [comment]
@fhqlatm 

# Site Front-End
찾아보니 submission 페이지는 아래 파일과 관련이 있는 듯 보입니다.

`/home/ubuntu/jota/site/judge/models/submission.py`

* **class Submission(models.Model):** # 전체적인 제출 결과 화면으로 예상됨
* **class SubmissionSource(models.Model):** # 소스코드 제출 화면
* **class SubmissionTestCase(models.Model):** # 테스트케이스 실행 결과

해보진 않았지만, 코드 수정 후 `(dmojsite) ~/jota/site$ python3 manage.py migrate` 실행하면 migration 하는 것 같습니다.

**Comment by fhqlatm** [comment]
[add: multiple files submission #15](https://github.com/hyunchan-park/JOTA-dmoj-online-judge/pull/15/files)

**Comment by fhqlatm** [comment]
## Implementation Completion Features

* [add: multiple files submission #15](https://github.com/hyunchan-park/JOTA-dmoj-online-judge/pull/15/files)
  * Multiple Files Submission: 다중 파일 형식의 답안 소스코드 제출
  * File upload User Interfaces: 파일 업로드 인터페이스 구현

* To be Modified
  * 기존 Text 형식 Source code 제출과의 충돌
  * DB 처리



## Additional Implementation Steps

* Source code viewer through Tabs
* Source code submission through Tabs



## Reference Documents

* [Reading Local Files in JavaScript](https://www.html5rocks.com/en/tutorials/file/dndfiles//#toc-reading-files)

* [File Reader & File API](https://developer.mozilla.org/en-US/docs/Web/API/Blob)
